public class Main {
    public static void main(String[] args) {
        byte apple = 1;
        short bananas = 130;
        int maracuias = 14;
        long daysInTheYear = 365L;
        float weight = (float) 61.7;
        double height = 175.9;
        System.out.println("Значение переменной apple с типом byte равно " + apple);
        System.out.println("Значение переменной bananas с типом short равно " + bananas);
        System.out.println("Значение переменной maracuias с типом int равно " + maracuias);
        System.out.println("Значение переменной daysInTheYear с типом long равно " + daysInTheYear);
        System.out.println("Значение переменной weight с типом float равно " + weight);
        System.out.println("Значение переменной height с типом double равно " + height);
        float f = 27.12f;
        long l = 987678965549L;
        double d = 2.786;
        short s1 = 569;
        short s2 = -159;
        int i = 27897;
        byte b = 67;
        byte ludmilaPavlovnaStudents = 23;
        byte annaSergeevnaStudents = 27;
        byte ekaterinaAndreevnaStudents = 30;
        int allTheStudents = ludmilaPavlovnaStudents + annaSergeevnaStudents + ekaterinaAndreevnaStudents;
        int papersForEveryStudent = 480 / allTheStudents;
        System.out.println("На каждого ученика рассчитано " + papersForEveryStudent + " листов бумаги");
        byte productivityPerMinute = 8;
        int productivityPer20Minutes = productivityPerMinute * 20;
        int productivityPer24H = productivityPerMinute * 24 * 60;
        int productivityPer3Days = productivityPerMinute * 24 * 60 * 3;
        int productivityPerMonth = productivityPerMinute * 24 * 60 * 30;
        System.out.println("За 20 минут машина произвела " + productivityPer20Minutes + " штук бутылок");
        System.out.println("За сутки машина произвела " + productivityPer24H + " штук бутылок");
        System.out.println("За 3 дня машина произвела " + productivityPer3Days + " штук бутылок");
        System.out.println("За месяц машина произвела " + productivityPerMonth + " штук бутылок");
        System.out.println();
        int whiteCanOfPaint = 2;
        int brownCanOfPaint = 4;
        int totalCansOfPaint = 120;
        int classesInTheSchool = totalCansOfPaint / (whiteCanOfPaint + brownCanOfPaint);
        int numberOfWhiteCan = classesInTheSchool * whiteCanOfPaint;
        int numberOfBrownCan = classesInTheSchool * brownCanOfPaint;
        System.out.println("В школе, где " + classesInTheSchool + " классов, нужно "
                + numberOfWhiteCan + " банок белой краски и " + numberOfBrownCan + " банок коричневой краски");
        int weightOfBananaInGram = 80;
        int numberOfBananas = 5;
        int weightOfIceCreamInGram = 100;
        int numberOfIceCreams = 2;
        int weightOfEggInGram = 70;
        int numberOfEggs = 4;
        int weightOfMilkInGram = 210;
        int weightOfSportBreakfast = weightOfBananaInGram * numberOfBananas + weightOfMilkInGram +
                weightOfIceCreamInGram * numberOfIceCreams + weightOfEggInGram * numberOfEggs;
        int kg = weightOfSportBreakfast / 1000;
        int g = weightOfSportBreakfast % 1000;
        System.out.println(kg + " килограмм " + g + " граммов");
        int kilo = 7;
        int kiloInGram = 7 * 1000;
        int gramInDay1 = 250;
        int gramInDay2 = 500;
        int days1 = kiloInGram / gramInDay1;
        System.out.println(days1 + " дней");
        int days2 = kiloInGram / gramInDay2;
        System.out.println(days2 + " дней");
        int daysInAverage = (days1 + days2)/2;
        System.out.println(daysInAverage + " день");
        int mashaSalary = 67_760;
        int denisSalary = 83_690;
        int kristinaSalary = 76_230;
        int newMashaSalary = mashaSalary * 10 / 100 + mashaSalary;
        int newDenisSalary = denisSalary * 10 / 100 + denisSalary;
        int newKristinaSalary = kristinaSalary * 10 / 100 + kristinaSalary;
        int incomeInYearMashaBefore = 67_760 * 12;
        int incomeInYearDenisBefore = denisSalary * 12;
        int incomeInYearKristinaBefore = kristinaSalary * 12;
        int incomeInYearMashaAfter = newMashaSalary * 12;
        int incomeInYearDenisAfter = newDenisSalary * 12;
        int incomeInYearKristinaAfter = newKristinaSalary * 12;
        int differenceMasha = incomeInYearMashaAfter - incomeInYearMashaBefore;
        int differenceDenis = incomeInYearDenisAfter - incomeInYearDenisBefore;
        int differenceKristina = incomeInYearKristinaAfter - incomeInYearKristinaBefore;
        System.out.println("Маша теперь получает " + newMashaSalary + " рублей. Годовой доход вырос на " + differenceMasha);
        System.out.println("Денис теперь получает " + newDenisSalary + " рублей. Годовой доход вырос на " + differenceDenis);
        System.out.println("Кристина теперь получает " + newKristinaSalary + " рублей. Годовой доход вырос на " + differenceKristina);
    }
}